# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    push:
        branches: [ "master" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        needs: cs
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: Build-Vue
                uses: xRealNeon/VuePagesAction@1.0.1
                with:
                    username: 'MacBim'
                    reponame: 'macbim.github.io'
                    token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
