name: CI

on:
    release:
        types: [ created ]

    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: Build-Vue
                uses: xRealNeon/VuePagesAction@1.0.1
                with:
                    username: 'MacBim'
                    reponame: 'macbim.github.io'
                    token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
