on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    cs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: install deps
                run: npm install

            -   name: eslint
                run: npm run lint

            -   name: type check
                run: npm run type-check

    #            -   name: tests e2e
    #                run: npm run test:e2e

    build-and-publish:
        needs: cs
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: Build-Vue
                uses: xRealNeon/VuePagesAction@1.0.1
                with:
                    username: 'MacBim'
                    reponame: 'macbim.github.io'
                    token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
